### ISSUE TITLE
Freezes extension host on large javascript files

### ISSUE THREAD

**Issue by forivall** [herrmannplatz/npm-dependency-links#15]
The parsing for document links in this extension is unnecessarily expensive, causes 100% cpu on the extension host, which causes all other extensions to become unresponsive. I tracked this down via extension bisect, it's this extension.

You can probably just remove the "javascript" from document links provider registration.

**Comment by herrmannplatz** [comment]
fixed with 🤞 https://github.com/herrmannplatz/npm-dependency-links/commit/af1957879f151c373798ffc29e05f573b3e8d6dd
