### ISSUE TITLE
Name of the extension on Visual Studio Marketplace

### ISSUE THREAD

**Issue by fharper** [herrmannplatz/npm-dependency-links#4]
It's a detail, but the name of the extension on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=herrmannplatz.npm-dependency-links) is "NPM Dependency Links", but npm name is always in lower case. It should be "npm Dependency Links".

P.S.: I know it's not in [the trademark policies](https://www.npmjs.com/policies/trademark), but we'll update the page with it as it should be there.

**Comment by fharper** [comment]
Oh, and thanks for the extension, I like it. I also [shared it on our community](https://npm.community/t/using-visual-studio-code-npm-dependency-links-extension-is-for-you/5140).

**Comment by fharper** [comment]
Actually, seems I was wrong... It's more of a marketing thing than a policy... Sorry for the spam!

**Comment by herrmannplatz** [comment]
So 

1. Good that there aren't any trademark policies.
2. Happy that you like it and im excited that you shared it.
3. Nevertheless i like consistency, so i check if i can rename it.

Thanks for your work! 🙌

**Comment by herrmannplatz** [comment]
Done
